version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: mssql
    environment:
      - ACCEPT_EULA=${MSSQL_ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_MSSQL_SA_PASSWORD}
      - TZ=${MSSQL_TZ}
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - mssql-network
volumes:
  mssql-data:
networks:
  mssql-network:
